// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    debugmodule: require("./debugmodule"),
    generateprocessmodule: require("./generateprocessmodule"),
    modulegenmodule: require("./modulegenmodule"),
    pathhandlermodule: require("./pathhandlermodule"),
    startupmodule: require("./startupmodule"),
    userinquirymodule: require("./userinquirymodule")
  };

  module.exports = Modules;

}).call(this);
