// Generated by CoffeeScript 2.4.1
(function() {
  var cliargumentsmodule, extractMeowed, getHelpText, getOptions, log, meow, throwErrorOnUsageFail;

  cliargumentsmodule = {
    name: "cliargumentsmodule"
  };

  //region node_modules
  meow = require('meow');

  //endregion

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["cliargumentsmodule"] != null) {
      console.log("[cliargumentsmodule]: " + arg);
    }
  };

  //region internal variables

  //endregion

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  cliargumentsmodule.initialize = function() {
    log("cliargumentsmodule.initialize");
  };

  //region internal functions
  getHelpText = function() {
    log("getHelpText");
    return "Usage\n    $ thingy-module-gen <arg1> <arg2>\n    \nOptions\n    required:\n        arg1, --name <module-name>, -n <module-name>\n        name of the module to be created                \n    \n    optional:\n        arg2, --thingy-path <path/to/thingy>, -p <path/to/thingy> [default: ./ ]\n        path to the root of the thingy. Usually it is cwd. Use it if you call this script from somewhere else.\n\nTO NOTE:\n    The flags will overwrite the flagless argument.\nExamples\n    $ thingy-module-gen  new-super-module \n    ...";
  };

  getOptions = function() {
    log("getOptions");
    return {
      flags: {
        name: {
          type: "string",
          alias: "n"
        },
        thingyPath: {
          type: "string",
          alias: "p"
        }
      }
    };
  };

  extractMeowed = function(meowed) {
    var name, thingyPath;
    log("extractMeowed");
    name = "";
    thingyPath = "";
    if (meowed.input[0]) {
      name = meowed.input[0];
    }
    if (meowed.input[1]) {
      thingyPath = meowed.input[1];
    }
    if (meowed.flags.name) {
      name = meowed.flags.name;
    }
    if (meowed.flags.thingyPath) {
      thingyPath = meowed.flags.thingyPath;
    }
    if (!thingyPath) {
      thingyPath = ".";
    }
    return {name, thingyPath};
  };

  throwErrorOnUsageFail = function(extract) {
    log("throwErrorOnUsageFail");
    if (!extract.name) {
      throw "Usage error: obligatory option name was not provided!";
    }
    if (!extract.thingyPath) {
      throw "fatal error: no default thingyPath was not available as fallback!";
    }
    if (!(typeof extract.name === "string")) {
      throw "Usage error: option name was provided in an unexpected way!";
    }
    if (!(typeof extract.thingyPath === "string")) {
      throw "Usage error: option thingyPath was provided in an unexpected way!";
    }
  };

  
  //endregion

  //region exposed functions
  cliargumentsmodule.extractArguments = function() {
    var extract, meowed, options;
    log("cliargumentsmodule.extractArguments");
    options = getOptions();
    meowed = meow(getHelpText(), getOptions());
    extract = extractMeowed(meowed);
    throwErrorOnUsageFail(extract);
    return extract;
  };

  //endregion exposed functions
  module.exports = cliargumentsmodule;

}).call(this);
