// Generated by CoffeeScript 2.5.1
(function() {
  var debugmodule;

  debugmodule = {
    name: "debugmodule"
  };

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  debugmodule.initialize = function() {};

  // console.log "debugmodule.initialize - nothing to do"
  debugmodule.modulesToDebug = {
    unbreaker: true
  };

  // cliargumentsmodule: true
  // configmodule: true
  // generateprocessmodule: true
  // modulegenmodule: true
  // pathhandlermodule: true
  // startupmodule: true
  // userinquirymodule: true
  // utilmodule: true

  //region exposed variables
  module.exports = debugmodule;

}).call(this);
