// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog, successMessage;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("generateprocessmodule"));

import c from 'chalk';

import * as userInquiry from "userinquirymodule.js";

import * as pathHandler from "pathhandlermodule.js";

import * as modulegen from "modulegenmodule.js";

//endregion

//#############################################################################
successMessage = function(arg) {
  return console.log(c.green(arg));
};

//#############################################################################
export var execute = async function(name, path) {
  var files;
  log("execute");
  await pathHandler.checkPaths(name, path);
  successMessage(" Module " + name + " may be created!");
  files = (await userInquiry.doInquiry());
  await modulegen.generate(files, name);
  return true;
};
