// Generated by CoffeeScript 2.4.1
(function() {
  var hookupmodule, log;

  hookupmodule = {
    name: "hookupmodule"
  };

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["hookupmodule"] != null) {
      console.log("[hookupmodule]: " + arg);
    }
  };

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  hookupmodule.initialize = function() {
    log("hookupmodule.initialize");
  };

  //region exposed functions
  hookupmodule.hookUpTheCoffee = function(moduleName) {
    log("hookupmodule.hookUpTheCoffee");
    log("moduleName: " + moduleName);
    return log("not implemented yet!");
  };

  hookupmodule.hookUpTheStyle = function(pugname) {
    log("hookupmodule.hookUpTheStyle");
    log("pugname: " + pugname);
    return log("not implemented yet!");
  };

  //endregion
  module.exports = hookupmodule;

}).call(this);
