// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var createQuestion, generateFileOptions, log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("userinquirymodule"));

import inquirer from "inquirer";

//#############################################################################
//region internal functions
generateFileOptions = function() {
  var options;
  options = [
    {
      name: ".coffee",
      checked: true
    },
    {
      name: ".pug"
    },
    {
      name: "styles.styl"
    }
  ];
  return options;
};

//#############################################################################
createQuestion = function(options) {
  return [
    {
      name: "filesToGenerate",
      type: "checkbox",
      message: "Which file do you need for this module?",
      choices: options
    }
  ];
};

//endregion

//#############################################################################
export var doInquiry = async function() {
  var answer, options, question;
  options = generateFileOptions();
  question = createQuestion(options);
  answer = (await inquirer.prompt(question));
  return answer.filesToGenerate;
};
