// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("utilmodule"));

import {
  //endregion

  //#############################################################################
  execFile,
  exec
} from 'child_process';

//#############################################################################
//region exports
export var isFullURL = function(url) {
  var checker;
  if (url.length < 20) {
    return false;
  }
  checker = url.substr(0, 8);
  if (checker === "https://") {
    return true;
  }
  if (checker === "git@gith") {
    return true;
  }
  return false;
};

//#############################################################################
export var capitaliseFirstLetter = function(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
};

//#############################################################################
export var execScriptPromise = function(script, options) {
  return new Promise(function(resolve, reject) {
    var callback;
    callback = function(error, stdout, stderr) {
      if (error) {
        reject(error);
      }
      if (stderr) {
        reject(new Error(stderr));
      }
      return resolve(stdout);
    };
    return execFile(script, options, callback);
  });
};

//#############################################################################
export var execGitCheckPromise = function(path) {
  var options;
  options = {
    cwd: path
  };
  return new Promise(function(resolve, reject) {
    var callback;
    callback = function(error, stdout, stderr) {
      if (error) {
        reject(error);
      }
      if (stderr) {
        reject(new Error(stderr));
      }
      return resolve(stdout);
    };
    return exec("git rev-parse --is-inside-work-tree", options, callback);
  });
};

//endregion
